services:
  traefik:
    image: traefik:v3.4
    container_name: traefik-proxy
    hostname: traefik-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik Dashboard
      - "8089:8089"  # WebSocket для WebRTC
      - "5060:5060/udp"  # SIP UDP
      - "5160:5160/tcp"  # SIP TCP
      - "18000-18100:18000-18100/udp"  # RTP диапазон
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt
      - traefik-logs:/var/log/traefik
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    environment:
      - TZ=Europe/Moscow
    command: --configFile=/etc/traefik/traefik.yml
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.stellaragents.ru`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      # Basic Auth for Dashboard
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2y$$05$$frVRoEe0Osjaj62zKs8Wl.6N7Re3w/6pRGdWSqDli9nKZmt5JVA0m"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  freepbx:
    build:
      context: ./docker/freepbx
      dockerfile: Dockerfile
    container_name: freepbx-server
    hostname: freepbx-server
    restart: unless-stopped
    # Порты проксируются через Traefik
    expose:
      - "80"     # HTTP для админки
      - "8089"   # WebSocket для WebRTC
      - "5060"   # SIP UDP
      - "5160"   # SIP TCP
    volumes:
      - freepbx-data:/data
      - freepbx-logs:/var/log
      - freepbx-www:/var/www/html
      - ./data/freepbx/backup:/backup
    environment:
      - TZ=Europe/Moscow
      - LIVEKIT_PUBLIC_IP=${LIVEKIT_PUBLIC_IP}
      - NOVOFON_USERNAME=${NOVOFON_USERNAME}
      - NOVOFON_PASSWORD=${NOVOFON_PASSWORD}
      - NOVOFON_NUMBER=${NOVOFON_NUMBER}
      - DB_HOST=freepbx-db
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asterisk_password
      - ENABLE_CRON=TRUE
      - ENABLE_SMTP=FALSE
      - RTP_START=18000
      - RTP_FINISH=18100
      - WEBROOT=/admin
    labels:
      - "traefik.enable=true"
      
      # HTTP Admin GUI
      - "traefik.http.routers.freepbx-admin.rule=Host(`pbx.stellaragents.ru`)"
      - "traefik.http.routers.freepbx-admin.entrypoints=websecure"
      - "traefik.http.routers.freepbx-admin.tls.certresolver=letsencrypt"
      - "traefik.http.services.freepbx-admin.loadbalancer.server.port=80"
      
      # Временный маршрут для тестирования с localhost
      - "traefik.http.routers.freepbx-test.rule=Host(`localhost`)"
      - "traefik.http.routers.freepbx-test.entrypoints=websecure"
      - "traefik.http.routers.freepbx-test.tls=true"
      - "traefik.http.routers.freepbx-test.service=freepbx-admin"
      
      # WebSocket для WebRTC (WSS 8089)
      - "traefik.http.routers.freepbx-wss.rule=Host(`pbx.stellaragents.ru`) && Path(`/ws`)"
      - "traefik.http.routers.freepbx-wss.entrypoints=wss"
      - "traefik.http.routers.freepbx-wss.tls.certresolver=letsencrypt"
      - "traefik.http.services.freepbx-wss.loadbalancer.server.port=8089"
      
      # SIP UDP 5060
      - "traefik.udp.routers.sip-udp.entrypoints=sip-udp"
      - "traefik.udp.routers.sip-udp.service=sip-udp-svc"
      - "traefik.udp.services.sip-udp-svc.loadbalancer.server.port=5060"
      
      # SIP TCP 5160
      - "traefik.tcp.routers.sip-tcp.entrypoints=sip-tcp"
      - "traefik.tcp.routers.sip-tcp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sip-tcp.service=sip-tcp-svc"
      - "traefik.tcp.services.sip-tcp-svc.loadbalancer.server.port=5160"


    networks:
      - traefik-public
      - default
    depends_on:
      - freepbx-db
      - redis
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin"]
      interval: 60s
      timeout: 30s
      retries: 5

  freepbx-db:
    image: mariadb:10.6
    container_name: freepbx-database
    hostname: freepbx-database
    restart: unless-stopped
    volumes:
      - freepbx-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asterisk_password
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  livekit-agent:
    build:
      context: ./configs/agent
      dockerfile: Dockerfile
    container_name: livekit-agent
    hostname: livekit-agent
    restart: unless-stopped
    volumes:
      - ./configs/agent:/app
      - ./data/agent:/data
      - ./data/logs/agent:/logs
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    depends_on:
      - redis
    command: ["start"]


  redis:
    image: redis:7-alpine
    container_name: redis-cache
    hostname: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  traefik-letsencrypt:
    driver: local
  traefik-logs:
    driver: local
  freepbx-data:
    driver: local
  freepbx-logs:
    driver: local
  freepbx-www:
    driver: local
  freepbx-db:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  traefik-public:
    external: true