services:
  freepbx:
    build:
      context: ./docker/freepbx
      dockerfile: Dockerfile
    container_name: freepbx-server
    hostname: freepbx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5060:5060/udp"
      - "5061:5061"
      - "18000-18100:18000-18100/udp"
    volumes:
      - freepbx-data:/data
      - freepbx-logs:/var/log
      - freepbx-www:/var/www/html
      - ./data/freepbx/backup:/backup
    environment:
      - TZ=Europe/Moscow
      - LIVEKIT_PUBLIC_IP=${LIVEKIT_PUBLIC_IP}
      - NOVOFON_USERNAME=${NOVOFON_USERNAME}
      - NOVOFON_PASSWORD=${NOVOFON_PASSWORD}
      - NOVOFON_NUMBER=${NOVOFON_NUMBER}
      - DB_HOST=freepbx-db
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asterisk_password
      - ENABLE_CRON=TRUE
      - ENABLE_SMTP=FALSE
      - RTP_START=18000
      - RTP_FINISH=18100
      - WEBROOT=/admin
    depends_on:
      - freepbx-db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/admin"]
      interval: 60s
      timeout: 30s
      retries: 5

  freepbx-db:
    image: mariadb:10.6
    container_name: freepbx-database
    hostname: freepbx-database
    restart: unless-stopped
    volumes:
      - freepbx-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asterisk_password
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  livekit-agent:
    build:
      context: ./configs/agent
      dockerfile: Dockerfile
    container_name: livekit-agent
    hostname: livekit-agent
    restart: unless-stopped
    volumes:
      - ./configs/agent:/app
      - ./data/agent:/data
      - ./data/logs/agent:/logs
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    depends_on:
      - redis
    command: ["start"]


  redis:
    image: redis:7-alpine
    container_name: redis-cache
    hostname: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  freepbx-data:
    driver: local
  freepbx-logs:
    driver: local
  freepbx-www:
    driver: local
  freepbx-db:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16